In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test,y_test) = mnist.load_data()
x_train = x_train/255.0
x_test = x_test/255.0

In [4]:
model = tf.keras.models.Sequential(
    [tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(.2),
    tf.keras.layers.Dense(10)
    ])

In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics = ['accuracy'])

In [8]:
model.fit(x_train,y_train,epochs=5,verbose=1)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2968 - accuracy: 0.9129
Epoch 2/5
1875/1875 [==============================] - 2s 995us/step - loss: 0.1444 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 2s 915us/step - loss: 0.1072 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 2s 913us/step - loss: 0.0879 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 2s 959us/step - loss: 0.0783 - accuracy: 0.9759


In [9]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 0s - loss: 0.0692 - accuracy: 0.9769 - 305ms/epoch - 976us/step


[0.06923599541187286, 0.9768999814987183]

In [10]:
np.set_printoptions(precision=3, suppress=True)
abalone_train = pd.read_csv(
    "https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",
    names=["Length", "Diameter", "Height", "Whole weight", "Shucked weight",
           "Viscera weight", "Shell weight", "Age"])

abalone_train.head()

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.435     0.335   0.110         0.334          0.1355          0.0775   
1   0.585     0.450   0.125         0.874          0.3545          0.2075   
2   0.655     0.510   0.160         1.092          0.3960          0.2825   
3   0.545     0.425   0.125         0.768          0.2940          0.1495   
4   0.545     0.420   0.130         0.879          0.3740          0.1695   

   Shell weight  Age  
0        0.0965    7  
1        0.2250    6  
2        0.3700   14  
3        0.2600   16  
4        0.2300   13

In [11]:
abalone_features = abalone_train.copy()
abalone_labels = abalone_features.pop('Age')
abalone_features = np.array(abalone_features)
abalone_features

array([[0.435, 0.335, 0.11 , ..., 0.136, 0.077, 0.097],
       [0.585, 0.45 , 0.125, ..., 0.354, 0.207, 0.225],
       [0.655, 0.51 , 0.16 , ..., 0.396, 0.282, 0.37 ],
       ...,
       [0.53 , 0.42 , 0.13 , ..., 0.374, 0.167, 0.249],
       [0.395, 0.315, 0.105, ..., 0.118, 0.091, 0.119],
       [0.45 , 0.355, 0.12 , ..., 0.115, 0.067, 0.16 ]])

In [12]:
abalone_model = tf.keras.Sequential([
    tf.keras.layers.Dense(64),
    tf.keras.layers.Dense(1)
])

In [13]:
abalone_model.compile(optimizer='adam',
                     loss=tf.keras.losses.MeanSquaredError(),
                     )

In [14]:
abalone_model.fit(abalone_features,abalone_labels,epochs=10)

Epoch 1/10
104/104 [==============================] - 0s 807us/step - loss: 63.8058
Epoch 2/10
104/104 [==============================] - 0s 726us/step - loss: 12.0988
Epoch 3/10
104/104 [==============================] - 0s 855us/step - loss: 8.2182
Epoch 4/10
104/104 [==============================] - 0s 777us/step - loss: 7.8063
Epoch 5/10
104/104 [==============================] - 0s 725us/step - loss: 7.4468
Epoch 6/10
104/104 [==============================] - 0s 777us/step - loss: 7.1579
Epoch 7/10
104/104 [==============================] - 0s 743us/step - loss: 6.9364
Epoch 8/10
104/104 [==============================] - 0s 777us/step - loss: 6.7798
Epoch 9/10
104/104 [==============================] - 0s 854us/step - loss: 6.6539
Epoch 10/10
104/104 [==============================] - 0s 795us/step - loss: 6.5520


In [15]:
normalize = tf.keras.layers.Normalization()

In [16]:
normalize.adapt(abalone_features)

In [17]:
abalone_features[:5]

array([[0.435, 0.335, 0.11 , 0.334, 0.136, 0.077, 0.097],
       [0.585, 0.45 , 0.125, 0.874, 0.354, 0.207, 0.225],
       [0.655, 0.51 , 0.16 , 1.092, 0.396, 0.282, 0.37 ],
       [0.545, 0.425, 0.125, 0.768, 0.294, 0.149, 0.26 ],
       [0.545, 0.42 , 0.13 , 0.879, 0.374, 0.17 , 0.23 ]])

In [18]:
norm_abalone_model = tf.keras.Sequential([
    normalize,
    abalone_model
])

In [19]:
norm_abalone_model.compile(optimizer='adam',loss=tf.keras.losses.MeanSquaredError(),metrics=['accuracy'])

In [20]:
norm_abalone_model.fit(abalone_features,abalone_labels,epochs=10)

Epoch 1/10
104/104 [==============================] - 0s 874us/step - loss: 80.2927 - accuracy: 0.0000e+00
Epoch 2/10
104/104 [==============================] - 0s 806us/step - loss: 17.4455 - accuracy: 0.0000e+00
Epoch 3/10
104/104 [==============================] - 0s 883us/step - loss: 8.6781 - accuracy: 0.0000e+00
Epoch 4/10
104/104 [==============================] - 0s 809us/step - loss: 6.7495 - accuracy: 0.0000e+00
Epoch 5/10
104/104 [==============================] - 0s 887us/step - loss: 6.0826 - accuracy: 0.0000e+00
Epoch 6/10
104/104 [==============================] - 0s 808us/step - loss: 5.6766 - accuracy: 0.0000e+00
Epoch 7/10
104/104 [==============================] - 0s 846us/step - loss: 5.3909 - accuracy: 3.0120e-04
Epoch 8/10
104/104 [==============================] - 0s 932us/step - loss: 5.2407 - accuracy: 3.0120e-04
Epoch 9/10
104/104 [==============================] - 0s 932us/step - loss: 5.1250 - accuracy: 3.0120e-04
Epoch 10/10
104/104 [=======================

In [21]:
titanic = pd.read_csv("https://storage.googleapis.com/tf-datasets/titanic/train.csv")
titanic.head()

survived     sex   age  n_siblings_spouses  parch     fare  class     deck  \
0         0    male  22.0                   1      0   7.2500  Third  unknown   
1         1  female  38.0                   1      0  71.2833  First        C   
2         1  female  26.0                   0      0   7.9250  Third  unknown   
3         1  female  35.0                   1      0  53.1000  First        C   
4         0    male  28.0                   0      0   8.4583  Third  unknown   

   embark_town alone  
0  Southampton     n  
1    Cherbourg     n  
2  Southampton     y  
3  Southampton     n  
4   Queenstown     y

In [22]:
titanic_features = titanic.copy()
titanic_labels = titanic_features.pop('survived')

In [23]:
input = tf.keras.Input(shape=(),dtype=tf.float32)
result = 2*input+1
result

<KerasTensor: shape=(None,) dtype=float32 (created by layer 'tf.__operators__.add')>

In [24]:
calc = tf.keras.Model(inputs=input,outputs=result)

In [25]:
print(calc(1).numpy())
print(calc(2).numpy())

3.0
5.0


In [26]:
inputs = {}
for name,column in titanic_features.items():
    dtype = column.dtype
    if dtype==object:
        dtype=tf.string
    else:
        dtype=tf.float32
    inputs[name] = tf.keras.Input(shape=(1,),name=name,dtype=dtype)
inputs

{'sex': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'sex')>,
 'age': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'age')>,
 'n_siblings_spouses': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'n_siblings_spouses')>,
 'parch': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'parch')>,
 'fare': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'fare')>,
 'class': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'class')>,
 'deck': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'deck')>,
 'embark_town': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'embark_town')>,
 'alone': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'alone')>}

In [27]:
numeric_inputs = {name:input for name,input in inputs.items() if input.dtype==tf.float32}
x = tf.keras.layers.Concatenate()(list(numeric_inputs.values()))
norm = tf.keras.layers.Normalization()
norm.adapt(np.array(titanic[numeric_inputs.keys()]))
all_numeric_inputs = norm(x)
all_numeric_inputs

<KerasTensor: shape=(None, 4) dtype=float32 (created by layer 'normalization_1')>

In [28]:
preprocessed_inputs = [all_numeric_inputs]

In [29]:
preprocessed_inputs

[<KerasTensor: shape=(None, 4) dtype=float32 (created by layer 'normalization_1')>]

In [30]:
for name,input in inputs.items():
    if input.dtype==tf.float32:
        continue
    lookup = tf.keras.layers.StringLookup(vocabulary=np.unique(titanic_features[name]))
    one_hot = tf.keras.layers.CategoryEncoding(num_tokens=lookup.vocabulary_size())
    x=lookup(input)
    x=one_hot(x)
    preprocessed_inputs.append(x)

In [31]:
preprocessed_inputs_cat = tf.keras.layers.Concatenate()(preprocessed_inputs)
titanic_preprocessing=tf.keras.Model(inputs,preprocessed_inputs_cat)
tf.keras.utils.plot_model(model=titanic_preprocessing, rankdir = 'LR', dpi=72, show_shapes=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model/model_to_dot to work.


In [32]:
titanic_features_dict = {name: np.array(value) for name,value in titanic_features.items()}

In [33]:
titanic_features_dict

{'sex': array(['male', 'female', 'female', 'female', 'male', 'male', 'female',
        'female', 'female', 'male', 'male', 'female', 'male', 'male',
        'female', 'female', 'male', 'male', 'female', 'male', 'male',
        'female', 'male', 'male', 'female', 'female', 'male', 'male',
        'male', 'male', 'female', 'female', 'female', 'male', 'female',
        'male', 'male', 'male', 'female', 'male', 'female', 'female',
        'male', 'male', 'female', 'male', 'male', 'male', 'female', 'male',
        'male', 'male', 'male', 'female', 'male', 'male', 'male', 'male',
        'male', 'male', 'male', 'male', 'female', 'male', 'male', 'female',
        'male', 'male', 'male', 'female', 'male', 'male', 'male', 'male',
        'male', 'male', 'female', 'male', 'female', 'male', 'male', 'male',
        'male', 'male', 'male', 'female', 'male', 'female', 'male',
        'female', 'male', 'male', 'male', 'male', 'male', 'male', 'female',
        'male', 'male', 'male', 'male', 'female',

In [39]:
features_dict = {name:values[:1] for name,values in titanic_features_dict.items()}
print(features_dict)
titanic_preprocessing(features_dict)

{'sex': array(['male'], dtype=object), 'age': array([22.]), 'n_siblings_spouses': array([1], dtype=int64), 'parch': array([0], dtype=int64), 'fare': array([7.25]), 'class': array(['Third'], dtype=object), 'deck': array(['unknown'], dtype=object), 'embark_town': array(['Southampton'], dtype=object), 'alone': array(['n'], dtype=object)}


<tf.Tensor: shape=(1, 28), dtype=float32, numpy=
array([[-0.61 ,  0.395, -0.479, -0.497,  0.   ,  0.   ,  1.   ,  0.   ,
         0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,
         0.   ,  0.   ,  1.   ,  0.   ]], dtype=float32)>

In [49]:
def titanic_model(preprocessing_head,inputs):
    body = tf.keras.Sequential([
        tf.keras.layers.Dense(64),
        tf.keras.layers.Dense(1)
    ])
    preprocessed_inputs = preprocessing_head(inputs)
    result = body(preprocessed_inputs)
    model = tf.keras.Model(inputs,result)
    model.compile(loss=tf.losses.BinaryCrossentropy(from_logits=True),
                 optimizer='adam')
    return model


In [50]:
titanic_model = titanic_model(titanic_preprocessing,inputs)

In [51]:
titanic_model.fit(x=titanic_features_dict,y=titanic_labels,epochs=10)

Epoch 1/10
20/20 [==============================] - 0s 800us/step - loss: 0.6620
Epoch 2/10
20/20 [==============================] - 0s 1ms/step - loss: 0.5500
Epoch 3/10
20/20 [==============================] - 0s 1ms/step - loss: 0.5009
Epoch 4/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4719
Epoch 5/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4529
Epoch 6/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4424
Epoch 7/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4339
Epoch 8/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4306
Epoch 9/10
20/20 [==============================] - 0s 842us/step - loss: 0.4259
Epoch 10/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4247


In [52]:
titanic_model.save('test')
reloaded = tf.keras.models.load_model('test')

INFO:tensorflow:Assets written to: test\assets


In [53]:
features_dict = {name:values[:1] for name, values in titanic_features_dict.items()}
before = titanic_model(features_dict)
after = reloaded(features_dict)
assert (before-after)<1e-3
print(before)
print(after)

tf.Tensor([[-1.894]], shape=(1, 1), dtype=float32)
tf.Tensor([[-1.894]], shape=(1, 1), dtype=float32)


In [55]:
import itertools

def slices(features):
    for i in itertools.count():#for each feature take index i
        example = {name:values[i] for name,values in features.items()}
        yield example

In [57]:
for example in slices(titanic_features_dict):
    for name,value in example.items():
        print(f'{name:19s}: {value}')
    break

sex                : male
age                : 22.0
n_siblings_spouses : 1
parch              : 0
fare               : 7.25
class              : Third
deck               : unknown
embark_town        : Southampton
alone              : n


In [63]:
features_ds = tf.data.Dataset.from_tensor_slices(titanic_features_dict)

In [59]:
for example in features_ds:
    for name,value in example.items():
        print(f'{name:19s}: {value}')
    break

sex                : b'male'
age                : 22.0
n_siblings_spouses : 1
parch              : 0
fare               : 7.25
class              : b'Third'
deck               : b'unknown'
embark_town        : b'Southampton'
alone              : b'n'


In [64]:
titanic_ds = tf.data.Dataset.from_tensor_slices((titanic_features_dict,titanic_labels))

In [65]:
titanic_batches = titanic_ds.shuffle(len(titanic_labels)).batch(32)

In [66]:
titanic_model.fit(titanic_batches,epochs=5)

Epoch 1/5
20/20 [==============================] - 0s 2ms/step - loss: 0.4226
Epoch 2/5
20/20 [==============================] - 0s 2ms/step - loss: 0.4222
Epoch 3/5
20/20 [==============================] - 0s 2ms/step - loss: 0.4205
Epoch 4/5
20/20 [==============================] - 0s 2ms/step - loss: 0.4223
Epoch 5/5
20/20 [==============================] - 0s 3ms/step - loss: 0.4208


In [67]:
titanic_file_path = tf.keras.utils.get_file("train.csv", "https://storage.googleapis.com/tf-datasets/titanic/train.csv")

40960/30874 [=======================================] - 0s 0us/step


In [70]:
titanic_csv_ds = tf.data.experimental.make_csv_dataset(
    titanic_file_path,
    batch_size=5,
    label_name='survived',
    num_epochs=1,
    ignore_errors=True
    )

In [75]:
for batch,label in titanic_csv_ds.take(1):
    for key,value in batch.items():
        print(f'{key:20s}: {value}')
    print()
    print(f"{'label':20s}: {label}")

sex                 : [b'female' b'male' b'male' b'female' b'male']
age                 : [35.   50.   28.    0.75 28.  ]
n_siblings_spouses  : [1 1 0 2 0]
parch               : [0 0 0 1 0]
fare                : [ 90.    106.425   7.25   19.258   7.896]
class               : [b'First' b'First' b'Third' b'Third' b'Third']
deck                : [b'C' b'C' b'unknown' b'unknown' b'unknown']
embark_town         : [b'Southampton' b'Cherbourg' b'Southampton' b'Cherbourg' b'Southampton']
alone               : [b'n' b'n' b'y' b'n' b'y']

label               : [1 0 0 1 0]


In [77]:
traffic_volume_csv_gz = tf.keras.utils.get_file(
    'Metro_Interstate_Traffic_Volume.csv.gz', 
    "https://archive.ics.uci.edu/ml/machine-learning-databases/00492/Metro_Interstate_Traffic_Volume.csv.gz",
    cache_dir='.', cache_subdir='traffic'
)

417792/405373 [==============================] - 0s 0us/step


In [80]:
traffic_volume_csv_gz_ds = tf.data.experimental.make_csv_dataset(
    traffic_volume_csv_gz,
    batch_size=256,
    label_name='traffic_volume',
    num_epochs=1,
    compression_type='GZIP'
)

for batch,label in traffic_volume_csv_gz_ds:
    for key,value in batch.items():
        print(f'{key:20s}: {value[:5]}')
    print(f"{'label':20s}: {label[:5]}")
    break

holiday             : [b'None' b'None' b'None' b'None' b'None']
temp                : [294.4  281.   272.99 297.2  269.6 ]
rain_1h             : [0.51 0.   0.   0.   0.  ]
snow_1h             : [0. 0. 0. 0. 0.]
clouds_all          : [ 8 90  1  1 90]
weather_main        : [b'Rain' b'Clouds' b'Clear' b'Clear' b'Clouds']
weather_description : [b'light rain' b'overcast clouds' b'sky is clear' b'sky is clear'
 b'overcast clouds']
date_time           : [b'2013-07-14 09:00:00' b'2012-10-19 12:00:00' b'2012-10-31 01:00:00'
 b'2013-05-09 14:00:00' b'2012-11-29 08:00:00']
label               : [2665 4489  346 5598 6072]


In [83]:
%%time
for i,(batch,label) in enumerate(traffic_volume_csv_gz_ds.repeat(20)):
    if i%40==0:
        print('.',end='')
print()

...............................................................................................
CPU times: total: 10.4 s
Wall time: 5.96 s


In [85]:
%%time
caching = traffic_volume_csv_gz_ds.cache().shuffle(1000)

for i,(batch,label) in enumerate(caching.shuffle(1000).repeat(20)):
    if i%40==0:
        print('.',end='')
print()

...............................................................................................
CPU times: total: 1.05 s
Wall time: 862 ms


In [86]:
%%time
snapshot = tf.data.experimental.snapshot('titanic.tfsnap')
snapshotting = traffic_volume_csv_gz_ds.apply(snapshot).shuffle(1000)
for i,(batch,label) in enumerate(snapshotting.shuffle(1000).repeat(20)):
    if i%40==0:
        print('.',end='')
print()

Instructions for updating:
Use `tf.data.Dataset.snapshot(...)`.
...............................................................................................
CPU times: total: 2.53 s
Wall time: 1.24 s


In [4]:
A = tf.constant([[1,2],[3,6]])

In [46]:
import datetime, warnings, scipy

In [48]:
import matplotlib as mpl
import seaborn as sns
import matplotlib.pyplot as plt

In [51]:
import math
from keras.models import Sequential
from keras.layers import LSTM, Dense
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_squared_error

In [54]:
df = pd.read_csv('air_quality.csv',sep=' ')
df.head()

No  Profile     Tanggal       Jam     O3    CO    NO2    SO2      NO  \
0   1  BANDUNG  2019-05-19  00:04:19  21.35  0.78   6.77  14.06  26.168   
1   2  BANDUNG  2019-05-19  00:15:01   5.93  0.82  14.87  17.23  53.853   
2   3  BANDUNG  2019-05-19  00:30:06   6.62  0.63  22.24   2.31  38.304   
3   4  BANDUNG  2019-05-19  00:49:19  13.29  0.44  19.00   5.32  18.962   
4   5  BANDUNG  2019-05-19  01:04:19   2.44  0.47  26.74  13.61  35.270   

      CO2  ...  PM4   PM10  TSP  TEMP    HUM     WS  WD  ISPU  Status  \
0  409.86  ...  0.0   2.77  0.0  21.4  100.0  0.600   5     9    BAIK   
1  394.79  ...  0.0  11.95  0.0  42.6  200.0  0.000   2    12    BAIK   
2  390.66  ...  0.0  12.71  0.0  63.6  299.2  0.000   2    13    BAIK   
3  401.23  ...  0.0   1.20  0.0  21.3   88.2  0.525   5     6    BAIK   
4  381.67  ...  0.0   3.52  0.0  21.3   97.4  0.975   5     9    BAIK   

   Unnamed: 22  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  

[5 rows x 23 columns]

In [56]:
def combine_date(df,tab_name):
    list_tab = []
    for i in range(df.shape[0]):
        list_tab.append(df.loc[i,'Tanggal']+'T'+df.loc[i,tab_name][0:2])
    return np.array(list_tab, dtype='datetime64')

df['Datetime'] = combine_date(df,'Jam')

In [59]:
df2 = df.groupby(['Datetime']).mean()
df2.head()

No         O3        CO     NO2      SO2        NO  \
Datetime                                                                    
2019-05-19 00:00:00   2.5  11.797500  0.667500  15.720   9.7300  34.32175   
2019-05-19 01:00:00   6.0   3.816667  0.373333  22.600  20.0900  39.82100   
2019-05-19 02:00:00   9.5   6.450000  0.332500  24.130  26.3100  51.29325   
2019-05-19 03:00:00  13.5   4.740000  0.180000  25.975  24.3900  43.51850   
2019-05-19 04:00:00  17.5  19.692500  0.202500  20.395  18.6225  53.37925   

                            CO2        VOC  PM1  PM2.5  PM4      PM10  TSP  \
Datetime                                                                     
2019-05-19 00:00:00  399.135000  439.22300  0.0    0.0  0.0  7.157500  0.0   
2019-05-19 01:00:00  388.536667  250.39400  0.0    0.0  0.0  3.293333  0.0   
2019-05-19 02:00:00  396.242500  251.04575  0.0    0.0  0.0  6.487500  0.0   
2019-05-19 03:00:00  401.355000  252.24875  0.0    0.0  0.0  4.700000  0.0   
2019-05-19 04:00:00  399.335000  694.23975  0.0    0.0  0.0  5.262500  0.0   

                          TEMP         HUM       WS        WD       ISPU  \
Datetime                                                                   
2019-05-19 00:00:00  37.225000  171.850000  0.28125  3.500000  10.000000   
2019-05-19 01:00:00  20.966667   95.033333  0.67500  4.666667  12.666667   
2019-05-19 02:00:00  20.150000   97.500000  0.09375  3.750000  16.250000   
2019-05-19 03:00:00  19.850000  100.000000  0.07500  5.000000  15.000000   
2019-05-19 04:00:00  53.475000  272.500000  0.18750  5.250000  13.250000   

                     Unnamed: 22  
Datetime                          
2019-05-19 00:00:00          NaN  
2019-05-19 01:00:00          NaN  
2019-05-19 02:00:00          NaN  
2019-05-19 03:00:00          NaN  
2019-05-19 04:00:00          NaN

In [65]:
df2.drop(index=[df2.index[0],df2.index[df2.shape[0]-1]],inplace=True)

In [66]:
df2.head()

No       O3      CO     NO2      SO2        NO  \
Datetime                                                                
2019-05-19 02:00:00   9.5   6.4500  0.3325  24.130  26.3100  51.29325   
2019-05-19 03:00:00  13.5   4.7400  0.1800  25.975  24.3900  43.51850   
2019-05-19 04:00:00  17.5  19.6925  0.2025  20.395  18.6225  53.37925   
2019-05-19 05:00:00  21.5  17.2400  0.2975  27.545  33.5400  52.43100   
2019-05-19 06:00:00  25.5  11.6125  0.7575  23.185  17.8325  37.16625   

                          CO2        VOC  PM1  PM2.5  PM4    PM10  TSP  \
Datetime                                                                 
2019-05-19 02:00:00  396.2425  251.04575  0.0    0.0  0.0  6.4875  0.0   
2019-05-19 03:00:00  401.3550  252.24875  0.0    0.0  0.0  4.7000  0.0   
2019-05-19 04:00:00  399.3350  694.23975  0.0    0.0  0.0  5.2625  0.0   
2019-05-19 05:00:00  393.2700  252.19325  0.0    0.0  0.0  6.5100  0.0   
2019-05-19 06:00:00  400.1100  252.05400  0.0    0.0  0.0  4.1750  0.0   

                       TEMP    HUM       WS    WD   ISPU  Unnamed: 22  
Datetime                                                               
2019-05-19 02:00:00  20.150   97.5  0.09375  3.75  16.25          NaN  
2019-05-19 03:00:00  19.850  100.0  0.07500  5.00  15.00          NaN  
2019-05-19 04:00:00  53.475  272.5  0.18750  5.25  13.25          NaN  
2019-05-19 05:00:00  18.050  100.0  0.24375  5.00  21.00          NaN  
2019-05-19 06:00:00  18.875   99.7  0.26250  5.00  12.00          NaN